Repository chooseadb/chooseadb.github.io, pull requests merged in 2025-05, with the labels that each got.

#16 Create CNAME
  CNAME
Labels: enhancement

#8 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement

#15 Add badges and some explaination of what this is.
  README.md
Labels: documentation

#23 Add all contributors
  .all-contributorsrc
  .prettierignore
  README.md
Labels: enhancement

#32 Sorry, @paddyroddy spotted typos in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: bug, documentation

#35 Fix link checking
  .lycheeignore
Labels: bug

#50 Line wrapping :)
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE.md
  README.md
Labels: documentation

#53 Add a CITATION.cff file.
  CITATION.cff
Labels: enhancement
